#include <iostream>
#include <stdexcept>

using std::runtime_error;
using std::cerr;


int main(){


    return 0;
}